In [6]:
%matplotlib inline

In [7]:
#%%bash
#conda install pytorch torchvision -c soumith


Tensors
=======

Tensors behave almost exactly the same way in PyTorch as they do in
Torch.

Create a tensor of size (5 x 7) with uninitialized memory:




In [11]:
import torch
a = torch.FloatTensor(5, 7)
print (a)

tensor([[4.7775e-17, 3.0854e-41, 1.3095e+10, 7.2053e+22, 4.7428e+30, 3.0881e+29,
         1.8499e+20],
        [5.0830e+31, 2.9588e+21, 7.1558e+22, 1.6045e+02, 1.6370e-19, 1.8617e+25,
         1.8936e+23],
        [1.6045e+02, 1.6370e-19, 1.8888e+31, 5.0848e+31, 1.8178e+31, 1.3556e-19,
         7.1463e+22],
        [4.6241e+30, 1.0552e+24, 1.9345e-19, 7.4086e+28, 4.9571e+28, 7.2251e+28,
         5.2487e-14],
        [2.3745e+23, 7.7764e+31, 2.7947e+20, 4.5925e+24, 1.7448e+22, 4.2325e+21,
         9.2246e-39]])


Initialize a tensor randomized with a normal distribution with mean=0, var=1:



In [12]:
a = torch.randn(5, 7)
print(a)
print(a.size())

tensor([[-1.0143,  1.5962,  0.6341,  0.9280, -2.6694,  1.2878,  1.6346],
        [-2.5934,  0.5811, -1.6028,  0.1085, -0.1649, -1.4704, -0.3940],
        [-0.7154, -1.0605,  2.0713,  0.8790, -0.4428,  0.0108, -1.6543],
        [ 4.2511, -2.0982,  0.6184,  1.5163,  0.1774, -1.7513,  0.3362],
        [ 0.2034, -1.2948,  0.5766,  1.0218, -0.4834, -1.3211,  2.3492]])
torch.Size([5, 7])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Inplace / Out-of-place
----------------------

The first difference is that ALL operations on the tensor that operate
in-place on it will have an ``_`` postfix. For example, ``add`` is the
out-of-place version, and ``add_`` is the in-place version.



In [13]:
a.fill_(3.5)
# a has now been filled with the value 3.5

b = a.add(4.0)
# a is still filled with 3.5
# new tensor b is returned with values 3.5 + 4.0 = 7.5

print(a, b)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000]]) tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]])


Some operations like ``narrow`` do not have in-place versions, and
hence, ``.narrow_`` does not exist. Similarly, some operations like
``fill_`` do not have an out-of-place version, so ``.fill`` does not
exist.

Zero Indexing
-------------

Another difference is that Tensors are zero-indexed. (In lua, tensors are
one-indexed)



In [15]:
b = a[0, 3]  # select 1st row, 4th column from a
print (b)

tensor(3.5000)


Tensors can be also indexed with Python's slicing



In [16]:
b = a[:, 3:5]  # selects all rows, 4th column and  5th column from a
print (b)

tensor([[3.5000, 3.5000],
        [3.5000, 3.5000],
        [3.5000, 3.5000],
        [3.5000, 3.5000],
        [3.5000, 3.5000]])


No camel casing
---------------

The next small difference is that all functions are now NOT camelCase
anymore. For example ``indexAdd`` is now called ``index_add_``



In [9]:
x = torch.ones(5, 5)
print(x)


 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
[torch.FloatTensor of size 5x5]



In [10]:
z = torch.Tensor(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)


  10  100
  10  100
  10  100
  10  100
  10  100
[torch.FloatTensor of size 5x2]



In [11]:
x.index_add_(1, torch.LongTensor([4, 0]), z)
print(x)


 101    1    1    1   11
 101    1    1    1   11
 101    1    1    1   11
 101    1    1    1   11
 101    1    1    1   11
[torch.FloatTensor of size 5x5]



Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.
The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [11]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [12]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [13]:
a.add_(1)
print(a)
print(b)	# see how the numpy array changed in value


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

CUDA Tensors are nice and easy in pytorch, and transfering a CUDA tensor
from the CPU to GPU will retain its underlying type.



In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    # creates a LongTensor and transfers it
    # to GPU as torch.cuda.LongTensor
    a = torch.LongTensor(10).fill_(3).cuda()
    print(type(a))
    b = a.cpu()
    # transfers it to CPU, back to
    # being a torch.LongTensor